enabled: true
overwrite: false
instrument: main

workflow:
  - step: beat_detection
    option: beat_this
  - step: music_metadata
    option: chord_recognition
  - step: separation
    option: bs_roformer_sw

instruments:
  - bass
  - drum
  - guitar
  - other
  - piano
