enabled: false
instrument: drums

workflow:
  - step: beat_detection
    option: madmom
  - step: separation
    option: bs_roformer_sw
  - step: audio_to_midi
    option: muscriptor_drum
  - step: music_metadata
    option: key_bpm_delay
  - step: music_metadata
    option: chord_recognition
  - step: midi_quantization
    option: default
