enabled: true
instrument: other

workflow:
  - step: beat_detection
    option: madmom
  - step: separation
    option: bs_roformer_sw
  - step: audio_to_midi
    option: muscriptor_other
  - step: music_metadata
    option: default
  - step: midi_quantization
    option: default
