enabled: true

key_bpm_delay:
  enabled: true
  algorithm: key_bpm_delay
  alignment_sample_count: 35

chord_recognition:
  enabled: true
  algorithm: chord_cnn_lstm
  repository_path: data/model/chord_cnn_lstm
  chord_dictionary: submission
