default_instrument: guitar
device: auto
dtype: auto

instruments:
  guitar:
    model: muscriptor
    checkpoint: medium
    target_instruments:
      - clean_electric_guitar
      # - acoustic_guitar
      # - distorted_electric_guitar
